# Generated by Django 3.0.8 on 2020-07-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insta_user_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.BigIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('biograghy', models.CharField(max_length=500)),
                ('profilepic_url', models.URLField()),
                ('external_url', models.URLField()),
                ('number_published', models.BigIntegerField()),
                ('number_followers', models.BigIntegerField()),
                ('number_follows', models.BigIntegerField()),
                ('is_private', models.BooleanField()),
                ('is_verified', models.BooleanField()),
            ],
        ),
    ]
