# Generated by Django 3.0.8 on 2020-08-03 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0002_auto_20200803_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_user_data',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insta_user.just_insta_id'),
        ),
    ]
