# Generated by Django 3.0.8 on 2020-08-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0003_auto_20200803_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_user_data',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='insta_user_data',
            name='profilepic_url',
            field=models.URLField(blank=True),
        ),
    ]
