# Generated by Django 3.0.8 on 2020-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0004_auto_20200803_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_user_data',
            name='biograghy',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
