# Generated by Django 3.0.8 on 2020-08-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0005_auto_20200803_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_user_data',
            name='id_number',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='insta_user_data',
            name='is_private',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='insta_user_data',
            name='is_verified',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='insta_user_data',
            name='number_followers',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='insta_user_data',
            name='number_follows',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='insta_user_data',
            name='number_published',
            field=models.BigIntegerField(blank=True),
        ),
    ]
