# Generated by Django 3.0.8 on 2020-08-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0006_auto_20200803_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_user_data',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
