# Generated by Django 3.0.8 on 2020-08-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0008_auto_20200803_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_user_data',
            name='biograghy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='insta_user_data',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
