# Generated by Django 3.0.8 on 2020-08-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0009_auto_20200803_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='just_insta_id',
        ),
        migrations.AlterField(
            model_name='insta_user_data',
            name='profilepic_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
