# Generated by Django 3.1 on 2020-08-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0011_auto_20200811_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insta_user_data',
            options={},
        ),
        migrations.AddIndex(
            model_name='insta_user_data',
            index=models.Index(fields=['number_followers'], name='insta_user__number__93a434_idx'),
        ),
    ]
