# Generated by Django 3.1 on 2020-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0012_auto_20200811_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='insta_user_data',
            name='rank',
            field=models.BigIntegerField(null=True),
        ),
    ]
