# Generated by Django 3.1 on 2020-08-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0013_insta_user_data_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_user_data',
            name='rank',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
