# Generated by Django 3.1 on 2020-08-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0015_auto_20200819_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_user_data',
            name='rank',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
