# Generated by Django 3.1 on 2020-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktok_user_data',
            name='id_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
